<a href="https://colab.research.google.com/github/kojikoji19780303/Cry_baby/blob/master/DAY7_%E8%A1%8C%E5%88%97%E7%A9%8D%E3%81%AE%E5%AE%9F%E8%A3%85_%E8%AA%B2%E9%A1%8C%E6%8F%90%E5%87%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

In [18]:
# 手計算
# -1*0 + 2*0 + 3*2
# -1*2 + 2*2 + 3*9 
# -1*1 + 2*-8 + 3*-1
# 4*0 + -5*0 +6*2 
# 4*2 + -5*2 +6*9
# 4*1 + -5*-8 +6*-1
# 7*0 + 8*0 + -9*2
# 7*2 + 8*2 + -9*9
# 7*1 + 8*-8 + -9*-1

In [25]:
a =-1*0 + 2*0 + 3*2
b = -1*2 + 2*2 + 3*9
c = -1*1 + 2*-8 + 3*-1
d =4*0 + -5*0 +6*2 
e =4*2 + -5*2 +6*9
f =4*1 + -5*-8 +6*-1
g =7*0 + 8*0 + -9*2
h =7*2 + 8*2 + -9*9
i =7*1 + 8*-8 + -9*-1
list=[a,b,c,d,e,f,g,h,i]
list

[6, 29, -20, 12, 52, 38, -18, -51, -48]

In [27]:
n_list = np.array(list)
n_list

array([  6,  29, -20,  12,  52,  38, -18, -51, -48])

In [31]:
n_array = n_list.reshape(3,3)
n_array

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

In [33]:
# np.matmul
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

a = np.matmul(a_ndarray, b_ndarray)
a

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装

In [35]:
#Aの0行目とBの0列目
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

mul00 = (a_ndarray[0,:]*b_ndarray[:, 0]).sum()
mul00

6

In [36]:
#Aの0行目とBの1列目
mul01 = (a_ndarray[0,:]*b_ndarray[:, 1]).sum()
mul01

29

【問題4】行列積を行う関数の作成

In [37]:
c = np.empty((2,2))
c

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [38]:
def gyouretuseki(a, b):

    c = np.empty((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i,:]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
gyouretuseki(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

4.行列積が定義されない組み合わせの行列

In [43]:
def gyouretuseki(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] == b.shape[0]: #aの列数とbの行数を比較し、等しい時だけ計算する。
        c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
        return c
    else:
        print("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
        return None
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(gyouretuseki(d, e)))

a.shape[1] != b.shape[0] : 3 != 2
計算結果
None


In [ ]:
【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [45]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

print("計算結果：\n{}".format(d.T@e))

計算結果：
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
